name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4 # Install Python
      with:
        python-version: 3.9  # Use the desired Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Update configsecrets.ini with API key
    - name: Update secrets 
      env:
        MERRIAM_WEBSTER_API_KEY: ${{ secrets.MERRIAM_WEBSTER_API_KEY }}
      run: |
        mkdir -p conf
        echo "[merriam-webster]" > conf/configsecrets.ini
        echo "api_key=${MERRIAM_WEBSTER_API_KEY}" >> conf/configsecrets.ini


    # Run linting
    - name: Run flake8
      run: flake8 app

    # Run tests
    - name: Run tests
      env:
        PYTHONPATH: app
      run: pytest app/merriam_webster_test.py -v > Merriam_Webster_Test_Artifact.txt
    
    # Upload test results as an artifact
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: Merriam_Webster_Test_Artifact.txt